name: pd-progression-external-validation
channels:
  - conda-forge
dependencies:
  - python>=3.10,<3.13
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - joblib
  - python-docx
  - pyyaml
  - openpyxl
  - jupyterlab
  - pip
